---
# tasks file for create_vm
- name: Create a VM with managed disk
  azure_rm_virtualmachine:
    resource_group: '{{ vm_resource_group }}'
    name: '{{ vm_name }}'
    vm_size: '{{ vm_size }}'
    admin_username: '{{ vm_admin_username }}'
    admin_password: '{{ vm_admin_password }}'
    network_interfaces: '{{ vm_network_interfaces }}'
    managed_disk_type: '{{vm_managed_disk_type}}'
    os_type: '{{vm_os_type}}'
    image:
      offer: '{{ vm_image_offer }}'
      publisher: '{{ vm_image_publisher }}'
      sku: '{{ vm_image_sku }}'
      version: '{{ vm_image_version }}'